---

- name: Install Debian dependencies
  apt:
    name: jq
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Download Pullio script from GitHub
  get_url:
    url: "{{ pullio_script_url }}"
    dest: "{{ pullio_script_install_path }}"
    mode: " {{ pullio_script_permissions }}"

